# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:3000/pizzaplaza_db_local
quarkus.datasource.username=root
quarkus.datasource.password=

# Hibernate / JPA
quarkus.hibernate-orm.database.generation-strategy=drop-and-create
quarkus.hibernate-orm.persistence-xml.ignore=true
quarkus.hibernate-orm.active=true
quarkus.hibernate-orm.packages=br.com.mosistemas.moentity,br.com.mosistemas.utils.portal,br.com.mosistemas.utils.utilscore.interfaces
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
quarkus.hibernate-orm.validate=true

# Opcional: scripts iniciais
quarkus.hibernate-orm.sql-load-script=br.com.pizzaplaza.orderservice.scripts.import.sql

# Pool de conexões
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.max-size=10
